# railway.toml

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = true

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[mounts]
# Optional: mounts if needed

[env]
# Environment variables set for your app (Browserless proxy flag)
DEFAULT_LAUNCH_ARGS = "--proxy-server=socks5://xiaomitinyproxy.ddns.net:48284"
