[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = true

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
DEFAULT_LAUNCH_ARGS = "--proxy-server=socks5://xiaomitinyproxy.ddns.net:48284"
BROWSER_DOMAIN_PRIVATE = "${{RAILWAY_PRIVATE_DOMAIN}}"
PREBOOT_QUANTITY = "0"
CONNECTION_TIMEOUT = "300000"
BROWSER_WS_ENDPOINT_PRIVATE = "ws://${{BROWSER_DOMAIN_PRIVATE}}:${{BROWSER_PORT_PRIVATE}}?token=${{BROWSER_TOKEN}}"
BROWSER_PLAYWRIGHT_ENDPOINT = "wss://${{BROWSER_DOMAIN}}/playwright?token=${{BROWSER_TOKEN}}"
BROWSER_PLAYWRIGHT_ENDPOINT_PRIVATE = "ws://${{BROWSER_DOMAIN_PRIVATE}}:${{BROWSER_PORT_PRIVATE}}/playwright?token=${{BROWSER_TOKEN}}"
BROWSER_WEBDRIVER_ENDPOINT_PRIVATE = "http://${{BROWSER_DOMAIN_PRIVATE}}:${{BROWSER_PORT_PRIVATE}}/webdriver"
BROWSER_DOMAIN = "${{RAILWAY_PUBLIC_DOMAIN}}"
BROWSER_PORT_PRIVATE = "3001"
TOKEN = "xoXLUD78cfzQNqWEpRNaFdECQc3k0KyC4tGZy27wmuvLCgxl"
BROWSER_TOKEN = "${{TOKEN}}"
KEEP_ALIVE = "false"
BROWSER_WEBDRIVER_ENDPOINT = "https://${{BROWSER_DOMAIN}}/webdriver"
PREBOOT_CHROME = "false"
ENABLE_CORS = "true"
MAX_QUEUE_LENGTH = "10"
BROWSER_WS_ENDPOINT = "wss://${{BROWSER_DOMAIN}}?token=${{BROWSER_TOKEN}}"
MAX_CONCURRENT_SESSIONS = "1"